name: Email new submission

on:
  push:
    paths:
      - 'submissions/**/*.py'

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Detect new .py file
        run: |
          FILE=$(jq -r '.head_commit.added[] | select(endswith(".py"))' < $GITHUB_EVENT_PATH)
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Send email with attachment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "📝 New submission: ${{ env.FILE }}"
          body: |
            New student submission received:
            • Repo: ${{ github.repository }}
            • Commit: ${{ github.sha }}
            • File: ${{ env.FILE }}
          to: sendhooran.a@trp.srmtrichy.edu.in    # ← UPDATE this!
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: ${{ env.FILE }}
